### ISSUE TITLE
README.md and other docs

### ISSUE THREAD

**Issue by rpatters1** [chrisroode/denigma#2]
I am working on a PR to add `README.md` and some other docs file to get the documentation started so that we can record our learnings here. (Or wherever here ends up.)

**Comment by chrisroode** [comment]
I've got some bullet points that are in my mind that I'll put together in a readme as well.  I'm thinking to keep it organized there will be a src folder for the c/c++ source, a deps folder for dependencies (mainly zlib) and then I have a nodeApp folder for the quick drafting that I am doing with nodejs.  I think maybe a documentation or docs folder would be good for the detail stuff about the file format.

Also, I would like to keep this repository focused on a CLI tool just to get the file into it's unpacked and unencrypted format.  What exactly is in the score.enigmaxml is beyond the scope of what this particular utility is for.

**Comment by rpatters1** [comment]
Closing as no longer relevant.
